---
name: "Container build and test"
on: [push, pull_request, workflow_call]
permissions: read-all

jobs:
  podman-build:
    name: Utility Container Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Utility Container Build
        run: make manifest podman-build-amd64

      - name: Run Container tests
        run: make test-amd64
